### ISSUE TITLE
[feat] 팀찾기, 팀원찾기 공통 컴포넌트 제작

### ISSUE THREAD

**Issue by sw2377** [codestates-seb/seb45_main_024#5]
### 🔖 공통 컴포넌트

- [x] card (front / back)
- [x] action button
- [x] search bar ( + 키워드 추가 input)
- [x] dropdown (형태 2가지)
- [x] checkbox
- [ ] pagination → 보류: 기능작업하면서 작업
- [x] tag (형태 2가지)

**Comment by kimD0ngjun** [comment]
번호 선점 너무해요
